### ISSUE TITLE
Running on non-multiplexed data

### ISSUE THREAD

**Issue by mjbeyeler** [MaestSi/ONTrack#1] opened 2019-08-07 11:12 UTC
Hello!

I was just wondering if this pipeline is hard-coded to only work with data from multiplexing protocols.

We have PromethION data that contain multiple samples in a single pool, and were wondering if we might still use your pipeline.

Best
Michael

**Comment by MaestSi** [comment] 2019-08-07 12:30
Hello!
If I understood correctly, you have some meta-barcoding samples, right? If this is the case no, the pipeline can't work with this kind of data. The only exception to this might be the case where you have pooled together a few single-organism samples and the organisms are quite different to each other; in this case I might suggest you how to run the pipeline. The last situation is similar to the case that we face when we sequence CO1 gene of an insect and we find out that in the sample there are also some parasites that are amplified as well by the universal primers.

**Comment by MaestSi** [comment] 2019-08-09 09:27
Hi, I have uploaded a script called MetatONTrack.sh, which is intended for Blasting each single read against the NCBI 16S Bacterial database (or whatever NCBI blast-indexed database) in a way similar to the EPI2ME 16S workflow, and saving to separate files reads assigned to different species. You can then run ONTrack.R on those files. Let me know if it works!

**Comment by mjbeyeler** [comment] 2019-08-09 11:59
You are right, we have meta-barcoding samples, and it would be very important to exactly determine each species. Sometimes they are very different, but this isn't always the case. (It's about border import control.)

So, if i understood you correctly this pipeline definitely won't work for us, unfortunately, or we'll have to add a multiplexing step to our experimental protocol.

But in any case thanks a bunch for your clarifications!

**Comment by MaestSi** [comment] 2019-08-09 13:21
As far as I know, the best approach for analysing a meta-barcoding sample composition using Oxford Nanopore reads, which have ~8% mean error rate, is just to Blast them against a database. This is reported to reach quite good accuracy at genus level, and a bit lower accuracy at species level. You can run this through the "official" EPI2ME 16S workflow, QIIME2 or the MetatONTrack.sh script, just to name a few. Using the latter option you also have the possibility to run afterwards ONTrack.R just on the reads that have been assigned to a species of interest for you by the previous Blast search.
I hope this helps, feel free to ask for any further clarification!

**Closed as completed** 2019-08-19 11:59 UTC
Labels: enhancement

**Comment by MaestSi** [comment] 2019-08-28 09:14
Hi, I just created a new GitHub repository called [MetONTIIME](https://github.com/MaestSi/MetONTIIME) that reproduces the EPI2ME 16S workflow in QIIME2 framework. Check it out if you want!
